module Foo.Bar.Main.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}


type NotificationPermission
    = Default
    | Denied
    | Granted



notificationPermissionDecoder : Decoder NotificationPermission
notificationPermissionDecoder =
    Decode.andThen
        (/tag ->
            case tag of
                "default" ->
                    Decode.succeed Default

                "denied" ->
                    Decode.succeed Denied

                "granted" ->
                    Decode.succeed Granted

        )
        Decode.string


type alias Flags =
    { currentTimeMillis : Float
    , notificationPermission : NotificationPermission
    }


flagsDecoder : Decoder Flags
flagsDecoder =
    Decode.todo "type alias"
