module Foo.Bar.Main.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}


type NotificationPermission
    = Default
    | Denied
    | Granted



notificationPermissionDecoder : Decoder NotificationPermission
notificationPermissionDecoder =
    Decode.andThen
        (/tag ->
            case tag of
                "default" ->
                    Decode.succeed Default

                "denied" ->
                    Decode.succeed Denied

                "granted" ->
                    Decode.succeed Granted

        )
        Decode.string


encodeNotificationPermission : NotificationPermission -> Encode.Value
encodeNotificationPermission notificationPermission =
    case notificationPermission of
        Default ->
            Encode.string "default"

        Denied ->
            Encode.string "denied"

        Granted ->
            Encode.string "granted"


type alias Flags =
    { currentTimeMillis : Float
    , notificationPermission : NotificationPermission
    }


flagsDecoder : Decoder Flags
flagsDecoder =
    Decode.map2 Flags
        (Decode.field "currentTimeMillis" Decode.float)
        (Decode.field "notificationPermission" notificationPermissionDecoder)


encodeFlags : Flags -> Encode.Value
encodeFlags flags =
    Encode.object
        [ ( "currentTimeMillis", Encode.float flags.currentTimeMillis )
        , ( "notificationPermission", encodeNotificationPermission flags.notificationPermission )
        ]
