module Foo.Bar.Main.Ports exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}


type alias AddNewPingAt =
    { value : Float
    }


type alias SetMinutesPerPing =
    { value : Float
    }


type alias SetTagForPing =
    { index : Float
    , value : Maybe String
    }


type ChangeDocument
    = AddNewPingAt AddNewPingAt
    | SetMinutesPerPing SetMinutesPerPing
    | SetTagForPing SetTagForPing



type alias V1 =
    { custom : Dict String String
    , tag : Maybe String
    , time : Int
    }


type PingsElements
    = V1 V1



type alias V1 =
    { minutesPerPing : Int
    }


type Settings
    = V1 V1



type alias V1 =
    { pings : List PingsElements
    , settings : Settings
    }


type DocFromAutomerge
    = V1 V1



type NotificationPermission
    = Default
    | Denied
    | Granted



type alias RequestNotificationPermission =
    ()


type alias NotificationOptions =
    { badge : Maybe String
    , body : Maybe String
    , icon : Maybe String
    , lang : Maybe String
    , requireInteraction : Maybe Bool
    , silent : Maybe Bool
    , tag : Maybe String
    }


type alias SendNotification =
    { options : NotificationOptions
    , title : String
    }
