module Main.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Json.Decode
import Json.Encode


type alias Flags =
    { eight : String
    , eleven : String
    , five : String
    , four : String
    , nine : String
    , one : String
    , seven : String
    , six : String
    , ten : String
    , three : String
    , twelve : String
    , two : String
    }


flagsDecoder : Decoder Flags
flagsDecoder =
    Json.Decode.map12 Flags
        (Json.Decode.field "eight" Json.Decode.string)
        (Json.Decode.field "eleven" Json.Decode.string)
        (Json.Decode.field "five" Json.Decode.string)
        (Json.Decode.field "four" Json.Decode.string)
        (Json.Decode.field "nine" Json.Decode.string)
        (Json.Decode.field "one" Json.Decode.string)
        (Json.Decode.field "seven" Json.Decode.string)
        (Json.Decode.field "six" Json.Decode.string)
        (Json.Decode.field "ten" Json.Decode.string)
        (Json.Decode.field "three" Json.Decode.string)
        (Json.Decode.field "twelve" Json.Decode.string)
        (Json.Decode.field "two" Json.Decode.string)


encodeFlags : Flags -> Json.Encode.Value
encodeFlags flags =
    Json.Encode.object
        [ ( "eight", Json.Encode.string flags.eight )
        , ( "eleven", Json.Encode.string flags.eleven )
        , ( "five", Json.Encode.string flags.five )
        , ( "four", Json.Encode.string flags.four )
        , ( "nine", Json.Encode.string flags.nine )
        , ( "one", Json.Encode.string flags.one )
        , ( "seven", Json.Encode.string flags.seven )
        , ( "six", Json.Encode.string flags.six )
        , ( "ten", Json.Encode.string flags.ten )
        , ( "three", Json.Encode.string flags.three )
        , ( "twelve", Json.Encode.string flags.twelve )
        , ( "two", Json.Encode.string flags.two )
        ]
