module Main.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Json.Decode
import Json.Decode.Pipeline
import Json.Encode


type alias Flags =
    { eight : String
    , eleven : String
    , five : String
    , four : String
    , nine : String
    , one : String
    , seven : String
    , six : String
    , ten : String
    , three : String
    , twelve : String
    , two : String
    }


flagsDecoder : Decoder Flags
flagsDecoder =
    Json.Decode.succeed Flags
        |> Json.Decode.Pipeline.required "eight" Json.Decode.string
        |> Json.Decode.Pipeline.required "eleven" Json.Decode.string
        |> Json.Decode.Pipeline.required "five" Json.Decode.string
        |> Json.Decode.Pipeline.required "four" Json.Decode.string
        |> Json.Decode.Pipeline.required "nine" Json.Decode.string
        |> Json.Decode.Pipeline.required "one" Json.Decode.string
        |> Json.Decode.Pipeline.required "seven" Json.Decode.string
        |> Json.Decode.Pipeline.required "six" Json.Decode.string
        |> Json.Decode.Pipeline.required "ten" Json.Decode.string
        |> Json.Decode.Pipeline.required "three" Json.Decode.string
        |> Json.Decode.Pipeline.required "twelve" Json.Decode.string
        |> Json.Decode.Pipeline.required "two" Json.Decode.string


encodeFlags : Flags -> Json.Encode.Value
encodeFlags flags =
    Json.Encode.object
        [ ( "eight", Json.Encode.string flags.eight )
        , ( "eleven", Json.Encode.string flags.eleven )
        , ( "five", Json.Encode.string flags.five )
        , ( "four", Json.Encode.string flags.four )
        , ( "nine", Json.Encode.string flags.nine )
        , ( "one", Json.Encode.string flags.one )
        , ( "seven", Json.Encode.string flags.seven )
        , ( "six", Json.Encode.string flags.six )
        , ( "ten", Json.Encode.string flags.ten )
        , ( "three", Json.Encode.string flags.three )
        , ( "twelve", Json.Encode.string flags.twelve )
        , ( "two", Json.Encode.string flags.two )
        ]
