// Warning: this file is automatically generated. Don't edit by hand!

declare module Elm {
  namespace Main {
    type Flags = {
      eight: string;
      eleven: string;
      five: string;
      four: string;
      nine: string;
      one: string;
      seven: string;
      six: string;
      ten: string;
      three: string;
      twelve: string;
      two: string;
    }
  
    type Ports = Record<string, never>
  
    function init(config: {
      flags: Flags;
      node: HTMLElement;
    }): void
  }
}