module Main.Ports exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}


type alias Logout =
    ()


logoutDecoder : Decoder Logout
logoutDecoder =
    Decode.null ()


encodeLogout : Logout -> Encode.Value
encodeLogout logout =
    {- TODO -}


type alias NewJwt =
    String


newJwtDecoder : Decoder NewJwt
newJwtDecoder =
    Decode.string


encodeNewJwt : NewJwt -> Encode.Value
encodeNewJwt newJwt =
    {- TODO -}
