module Main.Ports exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}


type alias Logout =
    ()


logoutDecoder : Decoder Logout
logoutDecoder =
    Decode.null ()


encodeLogout : Logout -> Encode.Value
encodeLogout logout =
    Encode.null


type alias NewJwt =
    String


newJwtDecoder : Decoder NewJwt
newJwtDecoder =
    Decode.string


encodeNewJwt : NewJwt -> Encode.Value
encodeNewJwt newJwt =
    Encode.string newJwt


port logout : Value -> Cmd msg


logout_ : TODO -> Cmd msg
logout_ value =
    Debug.todo "send"


port newJwt : Value -> Cmd msg


newJwt_ : TODO -> Cmd msg
newJwt_ value =
    Debug.todo "send"
