port module Main.Ports exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Json.Decode
import Json.Encode


type alias ElmToJs =
    { a : String
    }


elmToJsDecoder : Decoder ElmToJs
elmToJsDecoder =
    Json.Decode.map ElmToJs
        (Json.Decode.field "a" Json.Decode.string)


encodeElmToJs : ElmToJs -> Json.Encode.Value
encodeElmToJs elmToJs =
    Json.Encode.object
        [ ( "a", Json.Encode.string elmToJs.a )
        ]


type alias JsToElm =
    { a : String
    }


jsToElmDecoder : Decoder JsToElm
jsToElmDecoder =
    Json.Decode.map JsToElm
        (Json.Decode.field "a" Json.Decode.string)


encodeJsToElm : JsToElm -> Json.Encode.Value
encodeJsToElm jsToElm =
    Json.Encode.object
        [ ( "a", Json.Encode.string jsToElm.a )
        ]


port elmToJs : Value -> Cmd msg


elmToJs_ : ElmToJs -> Cmd msg
elmToJs_ value =
    elmToJs (encodeElmToJs value)


port jsToElm : (Value -> msg) -> Sub msg


jsToElm_ : (Result Json.Decode.Error JsToElm -> msg) -> Sub msg
jsToElm_ toMsg =
    jsToElm (/value -> toMsg (Json.Decode.decodeValue value jsToElmDecoder)
