module B.B2.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Json.Decode
import Json.Encode


type alias Flags =
    String


flagsDecoder : Decoder Flags
flagsDecoder =
    Json.Decode.string


encodeFlags : Flags -> Json.Encode.Value
encodeFlags flags =
    Json.Encode.string flags
