// Warning: this file is automatically generated. Don't edit by hand!

declare module Elm {
  namespace Main {
    type Flags = Record<string, never>
  
    type Ports = {
      toWorld: {
        subscribe: (callback: (value: {
          tag: "logout";
        } | {
          tag: "newJwt";
          value: string;
        }) => void) => void;
      };
    }
  
    function init(config: {
      flags: Flags;
      node: HTMLElement;
    }): {
      ports: Ports;
    }
  }
}