// Warning: this file is automatically generated. Don't edit by hand!

declare module Elm {
  namespace Main {
    type Flags = {
      currentJwt: string;
    }
    function init(config: {
      flags: Flags;
      node: HTMLElement;
    }): void
    type Ports = {
    }
  }
}