// Warning: this file is automatically generated. Don't edit by hand!

declare module Elm {
  namespace A {
    type Flags = string
  
    type Ports = Record<string, never>
  
    function init(config: {
      flags: Flags;
      node: HTMLElement;
    }): void
  }

  namespace B {
    type Flags = string
  
    type Ports = Record<string, never>
  
    function init(config: {
      flags: Flags;
      node: HTMLElement;
    }): void
  
    namespace B2 {
      type Flags = string
    
      type Ports = Record<string, never>
    
      function init(config: {
        flags: Flags;
        node: HTMLElement;
      }): void
    }
  }
}