// Warning: this file is automatically generated. Don't edit by hand!

declare module Elm {
  namespace Foo {
    namespace Bar {
      namespace Main {
        type Flags = {
          currentTimeMillis: number;
          notificationPermission: "default" | "denied" | "granted";
        }
        type Ports = {
        }
        function init(config: {
          flags: Flags;
          node: HTMLElement;
        }): void
      }
    }
  }
}