module Main.Flags exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Dict exposing (Dict)
import Json.Decode
import Json.Decode.Pipeline
import Json.Encode


type NotificationPermission
    = NotificationPermissionDefault
    | NotificationPermissionDenied
    | NotificationPermissionGranted


notificationPermissionDecoder : Json.Decode.Decoder NotificationPermission
notificationPermissionDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "default" ->
                    Json.Decode.succeed NotificationPermissionDefault

                "denied" ->
                    Json.Decode.succeed NotificationPermissionDenied

                "granted" ->
                    Json.Decode.succeed NotificationPermissionGranted

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        Json.Decode.string


encodeNotificationPermission : NotificationPermission -> Json.Encode.Value
encodeNotificationPermission notificationPermission =
    case notificationPermission of
        NotificationPermissionDefault ->
            Json.Encode.string "default"

        NotificationPermissionDenied ->
            Json.Encode.string "denied"

        NotificationPermissionGranted ->
            Json.Encode.string "granted"


type alias Flags =
    { currentTimeMillis : Float
    , notificationPermission : NotificationPermission
    }


flagsDecoder : Json.Decode.Decoder Flags
flagsDecoder =
    Json.Decode.succeed Flags
        |> Json.Decode.Pipeline.required "currentTimeMillis" Json.Decode.float
        |> Json.Decode.Pipeline.required "notificationPermission" notificationPermissionDecoder


encodeFlags : Flags -> Json.Encode.Value
encodeFlags flags =
    Json.Encode.object
        [ ( "currentTimeMillis", Json.Encode.float flags.currentTimeMillis )
        , ( "notificationPermission", encodeNotificationPermission flags.notificationPermission )
        ]
