port module Main.Ports exposing (..)

{-| Warning: this file is automatically generated. Don't edit by hand!
-}

import Dict exposing (Dict)
import Json.Decode
import Json.Decode.Pipeline
import Json.Encode


type alias AddNewPingAt =
    { value : Float
    }


addNewPingAtDecoder : Json.Decode.Decoder AddNewPingAt
addNewPingAtDecoder =
    Json.Decode.succeed AddNewPingAt
        |> Json.Decode.Pipeline.required "value" Json.Decode.float


encodeAddNewPingAt : AddNewPingAt -> Json.Encode.Value
encodeAddNewPingAt addNewPingAt_ =
    Json.Encode.object
        [ ( "value", Json.Encode.float addNewPingAt_.value )
        , ( "tag", Json.Encode.string "AddNewPingAt" )
        ]


type alias SetMinutesPerPing =
    { value : Float
    }


setMinutesPerPingDecoder : Json.Decode.Decoder SetMinutesPerPing
setMinutesPerPingDecoder =
    Json.Decode.succeed SetMinutesPerPing
        |> Json.Decode.Pipeline.required "value" Json.Decode.float


encodeSetMinutesPerPing : SetMinutesPerPing -> Json.Encode.Value
encodeSetMinutesPerPing setMinutesPerPing_ =
    Json.Encode.object
        [ ( "value", Json.Encode.float setMinutesPerPing_.value )
        , ( "tag", Json.Encode.string "SetMinutesPerPing" )
        ]


type alias SetTagForPing =
    { index : Float
    , value : Maybe String
    }


setTagForPingDecoder : Json.Decode.Decoder SetTagForPing
setTagForPingDecoder =
    Json.Decode.succeed SetTagForPing
        |> Json.Decode.Pipeline.required "index" Json.Decode.float
        |> Json.Decode.Pipeline.required "value" (Json.Decode.nullable Json.Decode.string)


encodeSetTagForPing : SetTagForPing -> Json.Encode.Value
encodeSetTagForPing setTagForPing_ =
    Json.Encode.object
        [ ( "index", Json.Encode.float setTagForPing_.index )
        , ( "value"
          , case setTagForPing_.value of
                Just value ->
                    Json.Encode.string value

                Nothing ->
                    Json.Encode.null
          )
        , ( "tag", Json.Encode.string "SetTagForPing" )
        ]


type ChangeDocumentElements
    = ChangeDocumentElementsAddNewPingAt AddNewPingAt
    | ChangeDocumentElementsSetMinutesPerPing SetMinutesPerPing
    | ChangeDocumentElementsSetTagForPing SetTagForPing


changeDocumentElementsDecoder : Json.Decode.Decoder ChangeDocumentElements
changeDocumentElementsDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "AddNewPingAt" ->
                    Json.Decode.map ChangeDocumentElementsAddNewPingAt addNewPingAtDecoder

                "SetMinutesPerPing" ->
                    Json.Decode.map ChangeDocumentElementsSetMinutesPerPing setMinutesPerPingDecoder

                "SetTagForPing" ->
                    Json.Decode.map ChangeDocumentElementsSetTagForPing setTagForPingDecoder

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        (Json.Decode.field "tag" Json.Decode.string)


encodeChangeDocumentElements : ChangeDocumentElements -> Json.Encode.Value
encodeChangeDocumentElements changeDocumentElements_ =
    case changeDocumentElements_ of
        ChangeDocumentElementsAddNewPingAt changeDocumentElementsAddNewPingAt ->
            encodeAddNewPingAt changeDocumentElementsAddNewPingAt

        ChangeDocumentElementsSetMinutesPerPing changeDocumentElementsSetMinutesPerPing ->
            encodeSetMinutesPerPing changeDocumentElementsSetMinutesPerPing

        ChangeDocumentElementsSetTagForPing changeDocumentElementsSetTagForPing ->
            encodeSetTagForPing changeDocumentElementsSetTagForPing


type alias ChangeDocument =
    List ChangeDocumentElements


changeDocumentDecoder : Json.Decode.Decoder ChangeDocument
changeDocumentDecoder =
    Json.Decode.list changeDocumentElementsDecoder


encodeChangeDocument : ChangeDocument -> Json.Encode.Value
encodeChangeDocument changeDocument_ =
    Json.Encode.list (/value -> encodeChangeDocumentElements value) changeDocument_


type alias Ping =
    { custom : Dict String String
    , tag : Maybe String
    , time : Int
    }


pingDecoder : Json.Decode.Decoder Ping
pingDecoder =
    Json.Decode.succeed Ping
        |> Json.Decode.Pipeline.required "custom" (Json.Decode.dict Json.Decode.string)
        |> Json.Decode.Pipeline.required "tag" (Json.Decode.nullable Json.Decode.string)
        |> Json.Decode.Pipeline.required "time" Json.Decode.int


encodePing : Ping -> Json.Encode.Value
encodePing ping_ =
    Json.Encode.object
        [ ( "custom", Json.Encode.dict identity (/value -> Json.Encode.string value) ping_.custom )
        , ( "tag"
          , case ping_.tag of
                Just value ->
                    Json.Encode.string value

                Nothing ->
                    Json.Encode.null
          )
        , ( "time", Json.Encode.int ping_.time )
        , ( "version", Json.Encode.string "v1" )
        ]


type PingsElements
    = VersionedPingsElementsV1 Ping


pingsElementsDecoder : Json.Decode.Decoder PingsElements
pingsElementsDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "v1" ->
                    Json.Decode.map VersionedPingsElementsV1 pingDecoder

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        (Json.Decode.field "version" Json.Decode.string)


encodePingsElements : PingsElements -> Json.Encode.Value
encodePingsElements pingsElements_ =
    case pingsElements_ of
        VersionedPingsElementsV1 versionedPingsElementsV1 ->
            encodePing versionedPingsElementsV1


type alias Settings =
    { minutesPerPing : Int
    }


settingsDecoder : Json.Decode.Decoder Settings
settingsDecoder =
    Json.Decode.succeed Settings
        |> Json.Decode.Pipeline.required "minutesPerPing" Json.Decode.int


encodeSettings : Settings -> Json.Encode.Value
encodeSettings settings_ =
    Json.Encode.object
        [ ( "minutesPerPing", Json.Encode.int settings_.minutesPerPing )
        , ( "version", Json.Encode.string "v1" )
        ]


type DocumentSettings
    = VersionedDocumentSettingsV1 Settings


documentSettingsDecoder : Json.Decode.Decoder DocumentSettings
documentSettingsDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "v1" ->
                    Json.Decode.map VersionedDocumentSettingsV1 settingsDecoder

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        (Json.Decode.field "version" Json.Decode.string)


encodeDocumentSettings : DocumentSettings -> Json.Encode.Value
encodeDocumentSettings documentSettings_ =
    case documentSettings_ of
        VersionedDocumentSettingsV1 versionedDocumentSettingsV1 ->
            encodeSettings versionedDocumentSettingsV1


type alias Doc =
    { pings : List PingsElements
    , settings : DocumentSettings
    }


docDecoder : Json.Decode.Decoder Doc
docDecoder =
    Json.Decode.succeed Doc
        |> Json.Decode.Pipeline.required "pings" (Json.Decode.list pingsElementsDecoder)
        |> Json.Decode.Pipeline.required "settings" documentSettingsDecoder


encodeDoc : Doc -> Json.Encode.Value
encodeDoc doc_ =
    Json.Encode.object
        [ ( "pings", Json.Encode.list (/value -> encodePingsElements value) doc_.pings )
        , ( "settings", encodeDocumentSettings doc_.settings )
        , ( "version", Json.Encode.string "v1" )
        ]


type DocFromAutomerge
    = VersionedDocFromAutomergeV1 Doc


docFromAutomergeDecoder : Json.Decode.Decoder DocFromAutomerge
docFromAutomergeDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "v1" ->
                    Json.Decode.map VersionedDocFromAutomergeV1 docDecoder

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        (Json.Decode.field "version" Json.Decode.string)


encodeDocFromAutomerge : DocFromAutomerge -> Json.Encode.Value
encodeDocFromAutomerge docFromAutomerge_ =
    case docFromAutomerge_ of
        VersionedDocFromAutomergeV1 versionedDocFromAutomergeV1 ->
            encodeDoc versionedDocFromAutomergeV1


type GotNewNotificationsPermission
    = GotNewNotificationsPermissionDefault
    | GotNewNotificationsPermissionDenied
    | GotNewNotificationsPermissionGranted


gotNewNotificationsPermissionDecoder : Json.Decode.Decoder GotNewNotificationsPermission
gotNewNotificationsPermissionDecoder =
    Json.Decode.andThen
        (/tag ->
            case tag of
                "default" ->
                    Json.Decode.succeed GotNewNotificationsPermissionDefault

                "denied" ->
                    Json.Decode.succeed GotNewNotificationsPermissionDenied

                "granted" ->
                    Json.Decode.succeed GotNewNotificationsPermissionGranted

                unknown ->
                    Json.Decode.fail ("Unknown value `" ++ unknown ++ "`")
        )
        Json.Decode.string


encodeGotNewNotificationsPermission : GotNewNotificationsPermission -> Json.Encode.Value
encodeGotNewNotificationsPermission gotNewNotificationsPermission_ =
    case gotNewNotificationsPermission_ of
        GotNewNotificationsPermissionDefault ->
            Json.Encode.string "default"

        GotNewNotificationsPermissionDenied ->
            Json.Encode.string "denied"

        GotNewNotificationsPermissionGranted ->
            Json.Encode.string "granted"


type alias Options =
    { badge : Maybe String
    , body : Maybe String
    , icon : Maybe String
    , lang : Maybe String
    , requireInteraction : Maybe Bool
    , silent : Maybe Bool
    , tag : Maybe String
    }


optionsDecoder : Json.Decode.Decoder Options
optionsDecoder =
    Json.Decode.succeed Options
        |> Json.Decode.Pipeline.optional "badge" (Json.Decode.nullable Json.Decode.string) Nothing
        |> Json.Decode.Pipeline.optional "body" (Json.Decode.nullable Json.Decode.string) Nothing
        |> Json.Decode.Pipeline.optional "icon" (Json.Decode.nullable Json.Decode.string) Nothing
        |> Json.Decode.Pipeline.optional "lang" (Json.Decode.nullable Json.Decode.string) Nothing
        |> Json.Decode.Pipeline.optional "requireInteraction" (Json.Decode.nullable Json.Decode.bool) Nothing
        |> Json.Decode.Pipeline.optional "silent" (Json.Decode.nullable Json.Decode.bool) Nothing
        |> Json.Decode.Pipeline.optional "tag" (Json.Decode.nullable Json.Decode.string) Nothing


encodeOptions : Options -> Json.Encode.Value
encodeOptions options_ =
    List.filterMap identity
        [ Maybe.map (/badge_ -> ( "badge", Json.Encode.string badge_ )) options_.badge
        , Maybe.map (/body_ -> ( "body", Json.Encode.string body_ )) options_.body
        , Maybe.map (/icon_ -> ( "icon", Json.Encode.string icon_ )) options_.icon
        , Maybe.map (/lang_ -> ( "lang", Json.Encode.string lang_ )) options_.lang
        , Maybe.map (/requireInteraction_ -> ( "requireInteraction", Json.Encode.bool requireInteraction_ )) options_.requireInteraction
        , Maybe.map (/silent_ -> ( "silent", Json.Encode.bool silent_ )) options_.silent
        , Maybe.map (/tag_ -> ( "tag", Json.Encode.string tag_ )) options_.tag
        ]
        |> Json.Encode.object


type alias Notify =
    { options : Options
    , title : String
    }


notifyDecoder : Json.Decode.Decoder Notify
notifyDecoder =
    Json.Decode.succeed Notify
        |> Json.Decode.Pipeline.required "options" optionsDecoder
        |> Json.Decode.Pipeline.required "title" Json.Decode.string


encodeNotify : Notify -> Json.Encode.Value
encodeNotify notify_ =
    Json.Encode.object
        [ ( "options", encodeOptions notify_.options )
        , ( "title", Json.Encode.string notify_.title )
        ]


type alias RequestNotificationsPermission =
    ()


requestNotificationsPermissionDecoder : Json.Decode.Decoder RequestNotificationsPermission
requestNotificationsPermissionDecoder =
    Json.Decode.null ()


encodeRequestNotificationsPermission : RequestNotificationsPermission -> Json.Encode.Value
encodeRequestNotificationsPermission requestNotificationsPermission_ =
    Json.Encode.null


port changeDocument : Json.Decode.Value -> Cmd msg


sendChangeDocument : ChangeDocument -> Cmd msg
sendChangeDocument =
    encodeChangeDocument >> changeDocument


port docFromAutomerge : (Json.Decode.Value -> msg) -> Sub msg


subscribeToDocFromAutomerge : (Result Json.Decode.Error DocFromAutomerge -> msg) -> Sub msg
subscribeToDocFromAutomerge toMsg =
    docFromAutomerge (Json.Decode.decodeValue docFromAutomergeDecoder >> toMsg)


port gotNewNotificationsPermission : (Json.Decode.Value -> msg) -> Sub msg


subscribeToGotNewNotificationsPermission : (Result Json.Decode.Error GotNewNotificationsPermission -> msg) -> Sub msg
subscribeToGotNewNotificationsPermission toMsg =
    gotNewNotificationsPermission (Json.Decode.decodeValue gotNewNotificationsPermissionDecoder >> toMsg)


port notify : Json.Decode.Value -> Cmd msg


sendNotify : Notify -> Cmd msg
sendNotify =
    encodeNotify >> notify


port requestNotificationsPermission : Json.Decode.Value -> Cmd msg


sendRequestNotificationsPermission : RequestNotificationsPermission -> Cmd msg
sendRequestNotificationsPermission =
    encodeRequestNotificationsPermission >> requestNotificationsPermission
